spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: report-api
          uri: http://${host.report}:${port.report}
          predicates:
            - Path=/report/**
          filters:
            - name: AuthFilter
        - id: access-control-api
          uri: http://${host.access-control}:${port.access-control}
          predicates:
            - Path=/employee/**
          filters:
            - name: AuthFilter
        - id: jwt-api
          uri: http://${host.jwt}:${port.jwt}
          predicates:
            - Path=/auth/**

logging:
  level:
    root: DEBUG

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8050/eureka/