spring:
  application:
    name: attendance-service

  profiles:
    active: kafka

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: attendance

logging:
  level:
    root: DEBUG

server:
  port: 8801