services:

  access-control-service:
    build: "./access-control-api"
    container_name: access-control-service
    ports:
      - 8801:8801
    networks:
      - local-net
    depends_on:
      - kafka

  report-service:
    build: "./report-api"
    container_name: 'report-service'
    ports:
      - 8802:8802
    networks:
      - local-net
    depends_on:
      - kafka
    environment:
      spring.kafka.bootstrap-servers: http://kafka:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - local-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
    name: local-net

