spring:
  application:
    name: report-api

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:report
  jpa:
    showSql: true
    hibernate:
      ddlAuto: create-drop

  profiles:
    active: kafka

server:
  port: 8801