apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: vijay2340025/api-gateway:latest
        name: gateway
        imagePullPolicy: Always
        env:
            - name: logging.level.root
              value: DEBUG

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
  - name: 30001
    port: 30001
    protocol: TCP
    targetPort: 8080
  selector:
    app: gateway
  type: LoadBalancer
