apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jwt
  name: jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt
  template:
    metadata:
      labels:
        app: jwt
    spec:
      containers:
      - image: vijay2340025/jwt:latest
        name: jwt
        imagePullPolicy: IfNotPresent
        env:
            - name: logging.level.root
              value: INFO
        
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jwt
  name: jwt
spec:
  ports:
  - name: 9898-9898
    nodePort: 30005
    port: 9898
    protocol: TCP
    targetPort: 9898
  selector:
    app: jwt
  type: NodePort
