spring:
  application:
    name: JWT-Service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:auth
  jpa:
    showSql: true
    hibernate:
      ddlAuto: create-drop

server:
  port: 9898


logging:
  level:
    root: DEBUG